config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  # root to: 'pages#about'
  # root to: 'pages#portfolio'
  get '/about', to: 'pages#about'
  get '/portfolio', to: 'pages#portfolio'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def portfolio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "conainter">
    <%#= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Noemie Lachman</h1>
<p>Fullstack Web Developer</p>

<h2>Education</h2>
  <p>Le Wagon</p>
  <p>Fullstack Web Development Bootcamp</p>
  <p>New York City</p>
  <p>Dates</p>
  <p>Description</p>

  <p>Korea University Business School</p>
  <p>Exchange Semester</p>
  <p>Seoul</p>
  <p>Dates</p>
  <p>Description</p>

  <p>Solvay Brussel School of Economics and Management</p>
  <p>Master's Degree in Management Science</p>
  <p>Brussels</p>
  <p>Dates</p>
  <p>Description</p>

  <p>Solvay Brussel School of Economics and Management</p>
  <p>Bachelor's Degree in Economics</p>
  <p>Brussels</p>
  <p>Dates</p>
  <p>Description</p>

<h2>Work Experience</h2>
  <p>Product Manager</p>
  <p>Butterfly.ai</p>
  <p>New York City</p>
  <p>Dates</p>
  <p>Description</p>

  <p>Business Intelligence Analyst</p>
  <p>Butterfly.ai</p>
  <p>New York City</p>
  <p>Dates</p>
  <p>Description</p>
<h2>Skills</h2>
<h2>Languages</h2>

app/views/pages/home.html.erb
<!-- <div>Picture of Me + Burger Menu</div> -->
<div class= "banner d-flex justify-content-between">
  <div class= "banner-text">
    <h1 id="title">Noémie Lachman</h1>
    <h3>Fullstack Web Developer</h3>
    <%= link_to "About Me", "#about", class: "button"%>
    <%= link_to "Reach Out", "#contact", class: "button"%>
  </div>
  <%= cl_image_tag("portfolio/noemie_fbszsd", height: '700px', class: "home-image") %>
</div>
<!-- <div>Quick Intro + CV download</div> -->
<div class= "description">
  <h1 id="about">About Me</h1>
  <p>After graduating from a Master Degree in Management Science, I started my career in B2Btech startup in NYC as a Product Manager. I then decided to learn to code. I am now a fullstack web developer and can help you bring your ideas to life with a combination of tech, business and product mindset
  </p>
  <p>After graduating from a Master Degree in Management Science, I started my career in B2Btech startup in NYC as a Product Manager. I then decided to learn to code. I am now a fullstack web developer and can help you bring your ideas to life with a combination of tech, business and product mindset
  </p>
  <p>After graduating from a Master Degree in Management Science, I started my career in B2Btech startup in NYC as a Product Manager. I then decided to learn to code. I am now a fullstack web developer and can help you bring your ideas to life with a combination of tech, business and product mindset
  </p>
  <p>Feel free to reach out</p>
</div>
<!-- <div>Links for contact</div> -->
<!-- <div>Dev Projects</div> -->
<div>
  <h1 style="text-align:center;" >My work</h1>
</div>
<div class = "projects row">
  <div class = "col">
    <div class="card-trip">
      <%= cl_image_tag("portfolio/Screenshot_2021-01-20_at_19.56.31_tjpjuu.png", height: '250px', class: "home-image") %>
      <div class="card-trip-infos">
        <div>
          <p>eTracker</p>
          <p>description</p>
          <p>Github</p>
          <p>Demo</p>
        </div>
      </div>
    </div>
  </div>
  <div class = "col">
    <div class="card-trip">
      <%= cl_image_tag("portfolio/Screenshot_2021-01-20_at_19.57.32_jhjeai.png", height: '250px', class: "home-image") %>
      <div class="card-trip-infos">
        <div>
          <p>DressBnB</p>
          <p>description</p>
          <p>Github</p>
        </div>
      </div>
    </div>
  </div>

  <div class = "col">
    <div class="card-trip">
      <%= cl_image_tag("portfolio/Screenshot_2021-01-20_at_19.57.00_bclvhi.png", height: '250px', class: "home-image") %>
      <div class="card-trip-infos">
        <div>
          <p>Archets Suzuki</p>
          <p>description</p>
          <p>Github</p>
          <p>Demo</p>
        </div>
      </div>
    </div>
  </div>

  <div class = "col">
    <div class="card-trip">
      <%= cl_image_tag("portfolio/Screenshot_2021-01-25_at_18.25.04_wjl1ot.png", height: '250px', class: "home-image") %>
      <div class="card-trip-infos">
        <div>
          <p>Locktails</p>
          <p>description</p>
          <p>Github</p>
          <p>Demo</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="contact">
  <h1 style="text-align:center;" >Get in touch</h1>
  <div class = "socials row">
    <%= link_to "", "https://www.linkedin.com/in/noemie-lachman-31035b119/", target: :_blank, class: "fab fa-linkedin col" %>
    <%= link_to "", "https://github.com/noemielach", target: :_blank, class: "fab fa-github col" %>
    <%= link_to "", "https://www.instagram.com/noemielach/?hl=fr", target: :_blank, class: "fab fa-instagram col" %>
    <%#= link_to "", "mail-to:noemie.lachman@hotmail.fr", :target => "_blank", class: "fas fa-at email col" %>
  </div>
</div>

app/views/pages/portfolio.html.erb
portfolio.html.erb

app/views/shared/_footer.html.erb
<div class = "footer-info">
  <p>Copyright - Noémie Lachman 2021</p>
</div>

app/views/shared/_navbar.html.erb
<%= link_to "Noémie Lachman", root_path, class: "nav-link" %>
<%= link_to "About Me", about_path, class: "nav-link" %>
<%= link_to "Work", portfolio_path, class: "nav-link" %>